/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
package parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int CHAVE_FECHA = 5;
  /** RegularExpression Id. */
  int CHAVE_ABRE = 6;
  /** RegularExpression Id. */
  int PAREN_FECHA = 7;
  /** RegularExpression Id. */
  int PAREN_ABRE = 8;
  /** RegularExpression Id. */
  int INTERROG = 9;
  /** RegularExpression Id. */
  int DOIS_PONTOS = 10;
  /** RegularExpression Id. */
  int PONTO_VIRG = 11;
  /** RegularExpression Id. */
  int IGUAL = 12;
  /** RegularExpression Id. */
  int DIFERENTE = 13;
  /** RegularExpression Id. */
  int NEGACAO = 14;
  /** RegularExpression Id. */
  int MENOR = 15;
  /** RegularExpression Id. */
  int MENOR_IGUAL = 16;
  /** RegularExpression Id. */
  int MAIOR = 17;
  /** RegularExpression Id. */
  int MAIOR_IGUAL = 18;
  /** RegularExpression Id. */
  int BARRA = 19;
  /** RegularExpression Id. */
  int ASTERISCO = 20;
  /** RegularExpression Id. */
  int VIRGULA = 21;
  /** RegularExpression Id. */
  int MENOS = 22;
  /** RegularExpression Id. */
  int MAIS = 23;
  /** RegularExpression Id. */
  int ATRIB = 24;
  /** RegularExpression Id. */
  int INCREMENTO = 25;
  /** RegularExpression Id. */
  int DECREMENTO = 26;
  /** RegularExpression Id. */
  int OR = 27;
  /** RegularExpression Id. */
  int AND = 28;
  /** RegularExpression Id. */
  int EXIBE = 29;
  /** RegularExpression Id. */
  int TRUE = 30;
  /** RegularExpression Id. */
  int FALSE = 31;
  /** RegularExpression Id. */
  int WHILE = 32;
  /** RegularExpression Id. */
  int DO = 33;
  /** RegularExpression Id. */
  int FOR = 34;
  /** RegularExpression Id. */
  int THEN = 35;
  /** RegularExpression Id. */
  int IF = 36;
  /** RegularExpression Id. */
  int ELSE = 37;
  /** RegularExpression Id. */
  int BEGIN_PROGRAM = 38;
  /** RegularExpression Id. */
  int END_PROGRAM = 39;
  /** RegularExpression Id. */
  int STRING = 40;
  /** RegularExpression Id. */
  int CHAR = 41;
  /** RegularExpression Id. */
  int ID = 42;
  /** RegularExpression Id. */
  int LITERAL_FLOAT = 43;
  /** RegularExpression Id. */
  int LITERAL_INT = 44;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\n\"",
    "\"\\t\"",
    "\"\\r\"",
    "\" \"",
    "\"}\"",
    "\"{\"",
    "\")\"",
    "\"(\"",
    "\"?\"",
    "\":\"",
    "\";\"",
    "\"==\"",
    "\"!=\"",
    "\"!\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"/\"",
    "\"*\"",
    "\",\"",
    "\"-\"",
    "\"+\"",
    "\":=\"",
    "\"++\"",
    "\"--\"",
    "\"||\"",
    "\"&&\"",
    "\"exibe\"",
    "\"False\"",
    "\"True\"",
    "\"while\"",
    "\"do\"",
    "\"for\"",
    "\"then\"",
    "\"if\"",
    "\"else\"",
    "\"$BEGIN_PROGRAM\"",
    "\"$END_PROGRAM\"",
    "<STRING>",
    "<CHAR>",
    "<ID>",
    "<LITERAL_FLOAT>",
    "<LITERAL_INT>",
  };

}
